#!/usr/bin/env python3
"""
Agent Comparison Test Runner

Sends the same coding exercise to different agents and collects results.
"""

import json
import subprocess
import time
from datetime import datetime
from pathlib import Path

# Read the exercise
EXERCISE_FILE = Path(__file__).parent / "agent_comparison_exercise.md"
with open(EXERCISE_FILE) as f:
    EXERCISE = f.read()

# Agents to test
AGENTS_TO_TEST = [
    {"name": "dev-backend-1", "type": "claude", "node": "local"},
    {"name": "dev-fullstack-1", "type": "gemini", "node": "local"},
    {"name": "pink-dev-1", "type": "gemini", "node": "pink-laptop"},
    {"name": "ollama-llama3", "type": "ollama", "model": "llama3"},
    {"name": "ollama-codellama", "type": "ollama", "model": "codellama:7b-instruct"},
]

RESULTS_DIR = Path(__file__).parent / "agent_comparison_results"
RESULTS_DIR.mkdir(exist_ok=True)

def send_to_distributed_agent(agent_name, exercise, node="local"):
    """Send exercise to a distributed agent via task router."""
    print(f"\n📋 Sending to {agent_name} ({node})...")

    # Create work directory
    work_dir = f"/tmp/agent_comparison_{agent_name}"
    Path(work_dir).mkdir(exist_ok=True)

    # Save exercise to work dir
    exercise_file = Path(work_dir) / "exercise.md"
    with open(exercise_file, "w") as f:
        f.write(exercise)

    # Send task via distributed task router
    cmd = [
        "python3",
        "distributed_task_router.py",
        "assign",
        f"Complete the coding exercise in {exercise_file}. Save your solution to {work_dir}/solution.py",
        work_dir,
        agent_name
    ]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
        print(f"   Task sent: {result.returncode == 0}")
        return work_dir
    except Exception as e:
        print(f"   Error: {e}")
        return None

def send_to_ollama(model_name, exercise):
    """Send exercise to Ollama model."""
    print(f"\n📋 Sending to Ollama ({model_name})...")

    prompt = f"{exercise}\n\nPlease provide the complete Python implementation:"

    cmd = ["ollama", "run", model_name, prompt]

    start_time = time.time()
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        elapsed = time.time() - start_time

        if result.returncode == 0:
            # Save result
            result_file = RESULTS_DIR / f"ollama_{model_name.replace(':', '_')}.py"
            with open(result_file, "w") as f:
                f.write(f"# Generated by Ollama {model_name}\n")
                f.write(f"# Time: {elapsed:.2f}s\n\n")
                f.write(result.stdout)

            print(f"   ✅ Completed in {elapsed:.2f}s")
            return str(result_file)
        else:
            print(f"   ❌ Failed: {result.stderr}")
            return None
    except subprocess.TimeoutExpired:
        print(f"   ⏱️  Timeout after 120s")
        return None
    except Exception as e:
        print(f"   ❌ Error: {e}")
        return None

def collect_distributed_agent_result(work_dir, agent_name, timeout=180):
    """Wait for and collect result from distributed agent."""
    print(f"   ⏳ Waiting for {agent_name} to complete (max {timeout}s)...")

    solution_file = Path(work_dir) / "solution.py"
    start_time = time.time()

    while time.time() - start_time < timeout:
        if solution_file.exists() and solution_file.stat().st_size > 100:
            # Result is ready
            with open(solution_file) as f:
                content = f.read()

            # Save to results
            result_file = RESULTS_DIR / f"{agent_name}.py"
            with open(result_file, "w") as f:
                f.write(f"# Generated by {agent_name}\n")
                f.write(f"# Time: {time.time() - start_time:.2f}s\n\n")
                f.write(content)

            print(f"   ✅ Collected result ({len(content)} chars)")
            return str(result_file)

        time.sleep(5)  # Check every 5 seconds

    print(f"   ⏱️  Timeout - no result after {timeout}s")
    return None

def main():
    """Run the comparison test."""
    print("="*70)
    print("🏆 AGENT COMPARISON TEST")
    print("="*70)
    print(f"Exercise: Smart Task Prioritizer")
    print(f"Results dir: {RESULTS_DIR}")
    print(f"Agents to test: {len(AGENTS_TO_TEST)}")
    print("="*70)

    results_summary = []

    for agent in AGENTS_TO_TEST:
        agent_name = agent["name"]
        agent_type = agent["type"]

        if agent_type == "ollama":
            # Direct Ollama execution
            result_file = send_to_ollama(agent["model"], EXERCISE)
            results_summary.append({
                "agent": agent_name,
                "type": agent_type,
                "model": agent["model"],
                "result_file": result_file,
                "status": "completed" if result_file else "failed"
            })

        else:
            # Distributed agent (claude/gemini)
            work_dir = send_to_distributed_agent(agent_name, EXERCISE, agent.get("node", "local"))

            if work_dir:
                # Note: Collection happens async - agents work independently
                results_summary.append({
                    "agent": agent_name,
                    "type": agent_type,
                    "work_dir": work_dir,
                    "status": "assigned"
                })

    # Save summary
    summary_file = RESULTS_DIR / "summary.json"
    with open(summary_file, "w") as f:
        json.dump({
            "timestamp": datetime.now().isoformat(),
            "exercise": "Smart Task Prioritizer",
            "agents": results_summary
        }, f, indent=2)

    print("\n" + "="*70)
    print("📊 SUMMARY")
    print("="*70)
    for r in results_summary:
        status_icon = "✅" if r["status"] in ["completed", "assigned"] else "❌"
        print(f"{status_icon} {r['agent']:20s} - {r['type']:10s} - {r['status']}")

    print(f"\n💾 Results will be saved to: {RESULTS_DIR}")
    print(f"📋 Summary: {summary_file}")
    print("\nFor distributed agents, check their work directories for solutions.")
    print("Ollama results are immediately available in the results directory.")

if __name__ == "__main__":
    main()
